const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const NEW_ATTACHMENT = "NEW_ATTACHMENT"
const NEW_REQUEST = "NEW_REQUEST"
const TYPING_STARTED = "TYPING_STARTED"
const TYPING_ENDED = "TYPING_ENDED"
const CURRENT_ONLINE_USERS = "CURRENT_ONLINE_USERS"
const USER_CONNECTED = "USER_CONNECTED"
const USER_DISCONNECTED = "USER_DISCONNECTED"
const MESSAGES_READ = "MESSAGES_READ"
const REFRESH_CHATLIST = "REFRESH_CHATLIST"


export { NEW_MESSAGE,MESSAGES_READ,REFRESH_CHATLIST, NEW_MESSAGE_ALERT, NEW_ATTACHMENT, NEW_REQUEST, TYPING_ENDED, TYPING_STARTED,CURRENT_ONLINE_USERS,USER_CONNECTED ,USER_DISCONNECTED}